### ISSUE TITLE
[BUG] nd2_to_tiff error: too many indices for array

### ISSUE THREAD

**Issue by eleonoraoliani** [ggirelli/radiantkit#156]
![Screenshot 2021-03-19 at 15 31 13](https://user-images.githubusercontent.com/74315737/111796483-8029ec80-88c8-11eb-85bd-e124bf882455.png)

**Comment by ggirelli** [comment]
Hi @eleonoraoliani , thanks for the report! :)

 I believe this issue was already fixed in the latest version. Can you check that you are using version `0.0.1.20210315.2` by running `radiant --version` and let me know? If you are using the latest version, I will investigate this further. If not, please upgrade to the latest by running `pipx install git+https://github.com/ggirelli/radiantkit.git --force` and let me know fi this fixes it.

Thanks again!
